package com.vm.entity;
// Generated May 4, 2019 7:35:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name="inventory"
    ,catalog="mydb"
)
public class Inventory  implements java.io.Serializable {


     private Integer idInventory;
     private Item item;
     private Integer stock;

    public Inventory() {
    }

	
    public Inventory(Item item) {
        this.item = item;
    }
    public Inventory(Item item, Integer stock) {
       this.item = item;
       this.stock = stock;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idInventory", unique=true, nullable=false)
    public Integer getIdInventory() {
        return this.idInventory;
    }
    
    public void setIdInventory(Integer idInventory) {
        this.idInventory = idInventory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Item_idItem", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

    
    @Column(name="Stock")
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }




}


