package com.vm.entity;
// Generated May 4, 2019 7:35:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Penjualan generated by hbm2java
 */
@Entity
@Table(name="penjualan"
    ,catalog="mydb"
)
public class Penjualan  implements java.io.Serializable {


     private Integer idPenjualan;
     private Integer totalSales;
     private Date tanggalPenjualan;
     private Set<PenjualanHasItem> penjualanHasItems = new HashSet<PenjualanHasItem>(0);

    public Penjualan() {
    }

	
    public Penjualan(Date tanggalPenjualan) {
        this.tanggalPenjualan = tanggalPenjualan;
    }
    public Penjualan(Integer totalSales, Date tanggalPenjualan, Set<PenjualanHasItem> penjualanHasItems) {
       this.totalSales = totalSales;
       this.tanggalPenjualan = tanggalPenjualan;
       this.penjualanHasItems = penjualanHasItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPenjualan", unique=true, nullable=false)
    public Integer getIdPenjualan() {
        return this.idPenjualan;
    }
    
    public void setIdPenjualan(Integer idPenjualan) {
        this.idPenjualan = idPenjualan;
    }

    
    @Column(name="totalSales")
    public Integer getTotalSales() {
        return this.totalSales;
    }
    
    public void setTotalSales(Integer totalSales) {
        this.totalSales = totalSales;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tanggalPenjualan", nullable=false, length=19)
    public Date getTanggalPenjualan() {
        return this.tanggalPenjualan;
    }
    
    public void setTanggalPenjualan(Date tanggalPenjualan) {
        this.tanggalPenjualan = tanggalPenjualan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="penjualan")
    public Set<PenjualanHasItem> getPenjualanHasItems() {
        return this.penjualanHasItems;
    }
    
    public void setPenjualanHasItems(Set<PenjualanHasItem> penjualanHasItems) {
        this.penjualanHasItems = penjualanHasItems;
    }




}


